language: android

android:
  components:
    - build-tools-28.0.3
    - android-15
    - android-17
    - android-27
    - android-28
  licenses:
    - 'android-sdk-license-.+'

# Prevent Travis from running automatic project install.
install:
  - true

script:
  - ./ci

deploy:
  skip_cleanup: true
  provider: script
  script: PUBLISH_RELEASE=true ./ci
  on:
    repo: lyft/Kronos-Android
    tags: true

before_cache:
  - rm -f "$HOME"/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper